services:
  grpctest:
    image: grpctest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - global_network
networks:
  global_network:
    external: 
      name: global_network